# Generated by Django 3.0.4 on 2020-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200325_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Images/no-image', upload_to='Images/'),
        ),
    ]
